### ISSUE TITLE
Choose and integrate a test framework

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#42]
### Description

Integrate a test suite harness into the UI Claim Tracker application. By default we are leaning towards [Jest](https://jestjs.io/) and [Enzyme](https://github.com/enzymejs/enzyme) like our [previous project](https://github.com/cagov/unemployment), but we should do a bit of research if there is some NextJS bonus or other best practice that has emerged.

### Acceptance Criteria

  - [x] Confirmed Jest is a reasonable choice for our project
  - [ ] Integrated Jest & Enzyme into the project base
  - [ ] Document choices in our [Technical Foundations doc](https://docs.google.com/document/d/1i2pj7_3n0VjqqztOepkd2VcG7JA8N9Tg5P76GSI8tzw/edit#) and README

**Comment by lomky** [comment]
[Example repo with Jest integration](https://github.com/vercel/next.js/tree/canary/examples/with-jest)

**Comment by lomky** [comment]
Reading on testing choices in js. Considering Jest, Mocha, and Jasmine

 - NextJS doesn't seem to have an opinion
 - [Jest vs Mocha: Which Should You Choose?](https://blog.usejournal.com/jest-vs-mocha-whats-the-difference-235df75ffdf3)
 - [NodeJS: Testing with Jest vs Mocha on Typescript in 2021](https://freddixx.medium.com/nodejs-testing-with-jest-vs-mocha-on-typescript-in-2021-7bffc28a4379)
 - [jasmine-vs-jest-vs-mocha](https://stackshare.io/stackups/jasmine-vs-jest-vs-mocha)
 - [jasmine docs](https://jasmine.github.io/pages/docs_home.html)

Conclusion: given our straightforward app I am choosing Jest for ease of setup. Mocha is more powerful but more setup effort, and I don't foresee us needing the extra power. Jasmine might be a good thing to come back to later if our backend app ends up with more complex logic we want to validate, but we can skip it for now since we aren't sure whether we're implementing that logic or it's being done directly in the DB.

**Comment by lomky** [comment]
Ran into a lot of issues with babel when adding Jest to NextJS 

Versions:
NextJS 10.0.9
React: 16.14.0
React-dom: 16.14.0

Error:
<details><summary>Error via `jest --ci --coverage`</summary>
Wed Mar 17 10:57:33 [kat/42_test_framework !?*] ~/repos/ui-claim-tracker $ yarn test         yarn run v1.21.1
$ jest --ci --coverage
 FAIL  pages/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /home/kat/repos/ui-claim-tracker/styles/Home.module.css: Unexpected token (1:0)

    > 1 | .container {
        | ^
      2 |   min-height: 100vh;
      3 |   padding: 0 0.5rem;
      4 |   display: flex;

      at Parser._raise (node_modules/@babel/parser/src/parser/error.js:97:45)
      at Parser.raiseWithData (node_modules/@babel/parser/src/parser/error.js:92:17)
      at Parser.raise (node_modules/@babel/parser/src/parser/error.js:41:17)
      at Parser.unexpected (node_modules/@babel/parser/src/parser/util.js:161:16)
      at Parser.parseExprAtom (node_modules/@babel/parser/src/parser/expression.js:1208:20)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/src/parser/expression.js:611:23)
      at Parser.parseUpdate (node_modules/@babel/parser/src/parser/expression.js:591:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/src/parser/expression.js:558:23)
      at Parser.parseExprOps (node_modules/@babel/parser/src/parser/expression.js:366:23)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/src/parser/expression.js:331:23)

</details>
<details><summary>error via `jest --watch`</summary>
Wed Mar 17 10:53:34 [kat/42_test_framework !?*] ~/repos/ui-claim-tracker $ yarn test:watch
yarn run v1.21.1
$ jest --watch

 FAIL  pages/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/kat/repos/ui-claim-tracker/styles/Home.module.css:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.container {
                                                                                             ^

    SyntaxError: Unexpected token .

      1 | import Head from 'next/head'
    > 2 | import styles from '../styles/Home.module.css'
        | ^
      3 |
      4 | export default function Home() {
      5 |   return (

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (pages/index.js:2:1)

</details>

Conclusion: integration with Jest 16.14 is different than previous versions. Solution

<details><summary>Worklog</summary>
ref https://dev.to/ericdouglas/how-to-configure-jest-on-a-next-js-project-1ic6
yarn add -D babel-jest jest
add the .babelrc
add teh test command

tests harness starts, but no tests yet sooo

_commit point, pr pushed_


added:
enzyme 
enzyme-adapter-react-16
jest-junit

Pulling ref files from https://github.com/cagov/unemployment/pull/31/files#
 - merging jest.config.js with existing
 - true'd up to that series of test run commands


 _commit point_

Realized I need it:
 - stole setupTestFramework.js from unemployment, pointed to it

tweak the commands to not have 
added `pages/_app.test.js based off of unemployment App test`

getting a css parse error?

```
$ yarn test
jest --ci --coverage
 FAIL  pages/_app.test.jest● Test suite failed to run
  ● Test suite failed to run

    SyntaxError: /home/kat/repos/ui-claim-tracker/styles/globals.css: Missing semicolon (2:4)

      1 | html, 
    > 2 | body {   
        |     ^   
```

https://stackoverflow.com/questions/56255074/nextjs-css-syntaxerror-unexpected-token
babel-jest should be fixing this for us? I must be configed wrong.

cleaning up the jest-config
 - dont want multiple roots
 - adding cssTransform.js 

no dice yet, same error

pulling out config for enzyme?
correcting app import?

okay, enzyme fully commented out, its not enzyme. something in our babel config is wrong. its parsing our CSS file as a JS file for some reason


going to try this solution: https://github.com/eddyerburgh/jest-transform-stub

adding jest-transform-stub
wait, also add babel?
no, babel-cli

updating config

no dice

2021-03-17

going back to looking at the working dir again and wtf is different


debugging with Kalvin
 - revieded work so far
 - more searching - discovered that _since fall 2020_ the behavior has changed!

 implemented https://stackoverflow.com/a/64689046/784829 and now working!
removed jest config
</details>

**Comment by lomky** [comment]
Quick research dive on Enzyme vs alternatives

Reading:
 - [Enzyme vs. react-testing-library: A mindset shift](https://blog.logrocket.com/enzyme-vs-react-testing-library-a-mindset-shift/)
 - [React: Test Renderer](https://www.npmjs.com/package/react-test-renderer)
 - [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)
 - [Enzyme](https://github.com/enzymejs/enzyme)
 - [AirBnB drops Enzyme ownership](https://www.infoq.com/news/2020/03/airbnb-drops-ownership-enzyme/)
 - [React 17 support status on Enzyme](https://github.com/enzymejs/enzyme/issues/2429)

Notes:
 - AirBnB moved Enzyme to a community run project last March with promises to still contibute to it, but the ~7 month process of getting support for React17 shows they seem to have left the developer on their own. 
 - there is lots of community support around React Testing Library
 - React Testing Library's approach of interacting with components from a real user perspective vs inspecting Dom is very appealing

Conclusions: 
 - react-testing-library's `toJson` capability makes for easy built-into-react snapshot testing - let's go with that.
 - I really like the perspective of testing components as users see them that React Testing Library gives - let's go with it
 - if we find down the line that we do really want the component-interals-interrogating we can also add enzyme alongside these then
