### ISSUE TITLE
Investigate `ApplicationInsights:Sender [   'Ingestion endpoint could not be reached.` issue

### ISSUE THREAD

**Issue by rocketnova** [cagov/ui-claim-tracker#502]
### Description

Today, we received a new Application Insights error:

```
ApplicationInsights:Sender [
  'Ingestion endpoint could not be reached. This batch of telemetry items has been lost. Use Disk Retry Caching to enable resending of failed telemetry. Error:',
  "[object Error]{ stack: 'Error: read ECONNRESET\n" +
    '    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)\n' +
    "    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14)', message: 'read ECONNRESET', name: 'Error'"
]
```

It looks like an `ECONNRESET` application error occurred, but Application Insights wasn't able to report it. I assume that Disk Retry Caching is on because we have the default configuration for `setUseDiskRetryCaching(true)`, but the issue appears to be coming from https://github.com/microsoft/ApplicationInsights-node.js/blob/52d3937bbb59d5bb29ecb04dc7fa1c06c04baafa/Library/Sender.ts#L292 which should only be happening if retries are disabled. (Note: this code snippet is not for the exact version we have locked right now, so there may be a discrepency happening there).

### Acceptance Criteria

- [ ] Investigate the issue
- [ ] Update this ticket with next steps if any

**Comment by rocketnova** [comment]
Closing. This issue has never recurred.
